### ISSUE TITLE
not shifting whole buffer

### ISSUE THREAD

**Issue by chefkoch009** [cjdelisle/buffershift#1] opened 2017-11-25 11:55 UTC
hi
buffershift only seems to shift 1 byte, but not the whole buffer:

Testcode: 
`const BufferShift = require('buffershift');

rotate();

function rotate(){
    var bufLen = 2;
    var buf = new Buffer(bufLen);
    buf[0] = 0x01;
    for (var k = 0; k < bufLen * 8; k++){
        console.log(k + '. Iteration with : ' + buf.toString('hex'));
        BufferShift.shl(buf, 1);
    }
}`

Result:
`0. Iteration with : 0100
1. Iteration with : 0200
2. Iteration with : 0400
3. Iteration with : 0800
4. Iteration with : 1000
5. Iteration with : 2000
6. Iteration with : 4000
7. Iteration with : 8000
8. Iteration with : 0000
9. Iteration with : 0000
10. Iteration with : 0000
11. Iteration with : 0000
12. Iteration with : 0000
13. Iteration with : 0000
14. Iteration with : 0000
15. Iteration with : 0000
`
But expecting:
`0. Iteration with : 0001
1. Iteration with : 0002
2. Iteration with : 0004
3. Iteration with : 0008
4. Iteration with : 0010
5. Iteration with : 0020
6. Iteration with : 0040
7. Iteration with : 0080
8. Iteration with : 0100
9. Iteration with : 0200
10. Iteration with : 0400
11. Iteration with : 0800
12. Iteration with : 1000
13. Iteration with : 2000
14. Iteration with : 4000
15. Iteration with : 8000`

kind regards

**Comment by cjdelisle** [comment] 2018-01-03 13:39
Sorry for the long wait, I think what you see is expected behavior because this is `shl` and not `rotl`. With `shl` the bits will fall off of the high side while with `rotl` they will loop around to the low side.

I'm going to close this for the moment but please feel free to reopen it if you see anything which seems to be wrong or if I misunderstood.

**Closed as completed by cjdelisle** 2018-01-03 13:39 UTC
